#!/bin/bash
# ============================================================
# update47.sh
# 新增「內線互撥」自訂 Dialplan 範本（限定分機清單，供 TC-ACSBC 等
# 自訂 context 使用），並修復兩個既有 bug：
#   1. TemplateCreateRequest.context 寫死 Literal["default","public"]，
#      導致範本模式完全無法寫入其他自訂 context（跟前端「Context 選單
#      支援任意既有 context」的實際行為互相矛盾，TC-ACSBC 也受影響）
#   2. list_custom_files() 只掃描 default/public，自訂 context 裡的
#      範本檔案永遠不會出現在列表
#   3. 新增輕量分機清單端點（不含密碼欄位），供範本表單勾選分機用
# 對應：changelog-details/20260811-internal-extension-template.md
#
# 修改檔案：routers/dialplan_custom.py（整份覆寫）、
#           static/js/dialplan.js（精確字串替換）
# ============================================================
set -e

cd "$(dirname "$0")"

BACKEND="routers/dialplan_custom.py"
FRONTEND="static/js/dialplan.js"

# --- 0. 自動歸檔：把非本次腳本的其他 updateN.sh 搬進固定資料夾 ---
ARCHIVE_DIR="updateN"
SELF="$(basename "$0")"

mkdir -p "$ARCHIVE_DIR"
for f in update*.sh; do
  [ "$f" = "$SELF" ] && continue
  [ -f "$f" ] || continue
  git mv "$f" "${ARCHIVE_DIR}/$f" 2>/dev/null || mv "$f" "${ARCHIVE_DIR}/$f"
done
git add update*.sh "$ARCHIVE_DIR"/ 2>/dev/null || true
if ! git diff --cached --quiet 2>/dev/null; then
  git commit -m "chore: 歸檔已執行的 updateN.sh 腳本"
fi

# --- 1. 前置驗證 ---
echo "[前置驗證] 確認兩個目標檔案目前內容符合預期（尚未套用本次改動）..."

for f in "$BACKEND" "$FRONTEND"; do
  if [ ! -f "$f" ]; then
    echo "❌ 找不到 $f" >&2
    exit 1
  fi
done

if grep -q "internal_extension" "$BACKEND"; then
  echo "❌ $BACKEND 已包含 internal_extension，本次改動可能已套用過，中止避免重複套用" >&2
  exit 1
fi

if grep -q '_dcPopulateDynamicFields' "$FRONTEND"; then
  echo "❌ $FRONTEND 已包含 _dcPopulateDynamicFields，本次改動可能已套用過，中止避免重複套用" >&2
  exit 1
fi

if ! grep -q 'context: Literal\["default", "public"\]' "$BACKEND"; then
  echo "❌ $BACKEND 內容與預期的舊版不符（找不到比對錨點），請先確認檔案目前實際內容，不要假設等於文件記錄的版本" >&2
  exit 1
fi

echo "  ✓ 前置驗證通過"

# --- 2. routers/dialplan_custom.py：整份覆寫（base64 還原，避免 SSH heredoc 貼上內容被截斷/打亂）---
echo "[Step 1] 覆寫 $BACKEND..."
cp "$BACKEND" "${BACKEND}.pre-update47.bak"

echo "IiIiCkRpYWxwbGFuIOiHquWumue+qeeuoeeQhu+8iOmhnuWei+S4ie+8muevhOacrCArIOaXouaciSBYTUwg57eo6Lyv5Zmo77yJCj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0K6IiH6aGe5Z6L5LiAIC8g6aGe5Z6L5LqM55qE5YiG5bel77yaCiAgLSDpoZ7lnovkuIDvvIhkaWFscGxhbl9yb3V0ZXMucHnvvInvvJowMF9yb3V0ZV8qLnhtbO+8jOihqOWWruWMluWkluaSpei3r+eUsQogIC0g6aGe5Z6L5LqM77yIZGlhbHBsYW5fc3lzdGVtX2V4dGVuc2lvbnMucHnvvInvvJpkZWZhdWx0LnhtbCAvIHB1YmxpYy54bWzvvIzllK/oroAKICAtIOmhnuWei+S4ie+8iOacrOaqlO+8ie+8muWFtumkmOaJgOacieiHquWumue+qSBkaWFscGxhbiBYTUwg5qqU5qGICiAgICAgIMK3IOevhOacrOaooeW8j++8mumBuOevhOacrCDihpIg5aGr6KGo5ZauIOKGkiDkvp0gc2NoZW1hIOeUoueUnyBYTUzvvIjmnKzmqpTosqDosqzvvIkKICAgICAgwrcg5omL5YuV5qih5byP77ya5pei5pyJ55qEIHJhdyB0ZXh0YXJlYSDnt6jovK/lmajvvIzmsr/nlKggc2VydmVyLnB5IOePvuacieeahAogICAgICAgIEdFVC9QT1NUL0RFTEVURSAvYXBpL2RpYWxwbGFuL2ZpbGUg6IiHIFBPU1QgL2FwaS9kaWFscGxhbi9jcmVhdGXvvIwKICAgICAgICDmnKzmqpTkuI3ph43opIflr6bkvZzvvIzlj6rlnKjliJfooaggQVBJIOijoeaKiumAmeS6m+aqlOahiOS4gOS9teWIl+WHuuOAggoK5paw5aKe56+E5pys5Y+q6ZyA6KaB5ZyoIFRFTVBMQVRFUyDoo6HliqDkuIDnrYbvvIhmaWVsZHMgKyBnZW5lcmF0b3LvvInvvIwK5LiN6ZyA6KaB5pu05YuV5Lu75L2V6Lev55Sx5oiW5YmN56uv5qGG5p6256iL5byP56K877yI5YmN56uv5L6dIGZpZWxkcyBzY2hlbWEg5YuV5oWL55Si55Sf6KGo5Zau77yJ44CCCiIiIgoKaW1wb3J0IG9zCmltcG9ydCByZQppbXBvcnQganNvbgppbXBvcnQgZ2xvYgpmcm9tIHR5cGluZyBpbXBvcnQgT3B0aW9uYWwsIExpdGVyYWwKCmZyb20gZmFzdGFwaSBpbXBvcnQgQVBJUm91dGVyLCBIVFRQRXhjZXB0aW9uLCBCb2R5LCBEZXBlbmRzCmZyb20gcHlkYW50aWMgaW1wb3J0IEJhc2VNb2RlbCwgZmllbGRfdmFsaWRhdG9yCmZyb20gbHhtbCBpbXBvcnQgZXRyZWUKCmZyb20gY29yZS5kaWFscGxhbl9jb21tb24gaW1wb3J0IG1ha2VfYmFja3VwLCByZWxvYWRfYW5kX3ZlcmlmeSwgcm9sbGJhY2tfbmV3X2ZpbGUsIHZhbGlkYXRlX3htbApmcm9tIGNvcmUuYXV0aCBpbXBvcnQgcmVxdWlyZV9wZXJtaXNzaW9uCmZyb20gY29yZS5wZXJtaXNzaW9ucyBpbXBvcnQgTW9kdWxlCgpyb3V0ZXIgPSBBUElSb3V0ZXIoKQoKRElBTFBMQU5fUk9PVCA9ICIvZXRjL2ZyZWVzd2l0Y2gvZGlhbHBsYW4iCk1FVEFfUkUgPSByZS5jb21waWxlKHIiPCEtLVxzKkRBU0hCT0FSRF9DVVNUT01fTUVUQTpccyooXHsuKj9cfSlccyotLT4iLCByZS5ET1RBTEwpCgojIOiIhyByb3V0ZXJzL2V4dGVuc2lvbnMucHkg55qEIEVYVF9ESVIg55u45ZCM6Lev5b6R77yM5q2k6JmV542o56uL5a6j5ZGK5LiA5Lu95bi45pW45Y+q5piv54K65LqGCiMg6YG/5YWN6LeoIHJvdXRlciBpbXBvcnTvvIjmnKzmqpTlj6rpnIDopoHllK/oroDmjoPmj4/vvIzkuI3pnIDopoEgZXh0ZW5zaW9ucy5weSDnmoTlhbbku5bpgo/ovK/vvIkKRVhUX0RJUiA9ICIvZXRjL2ZyZWVzd2l0Y2gvZGlyZWN0b3J5L2RlZmF1bHQiCgojIOeUseWFtuS7lumggemdoueuoeeQhueahOaqlOahiOWJjee2tO+8j+aqlOWQje+8jOmhnuWei+S4ieeahOWIl+ihqOimgeaOkumZpO+8jOmBv+WFjemHjeikh+euoeeQhuWFpeWPowpNQU5BR0VEX1BSRUZJWEVTID0gKCIwMF9yb3V0ZV8iLCAiMDBfZ3JvdXBfIiwgIjAwX2l2cl8iKQpNQU5BR0VEX0ZJTEVOQU1FUyA9ICgiZGVmYXVsdC54bWwiLCAicHVibGljLnhtbCIpCgoKIyDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZAKIyDnr4TmnKwgU2NoZW1hIOWumue+qQojIOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkAoKY2xhc3MgVGVtcGxhdGVGaWVsZChCYXNlTW9kZWwpOgogICAga2V5OiBzdHIKICAgIGxhYmVsOiBzdHIKICAgIHR5cGU6IExpdGVyYWxbInRleHQiLCAibnVtYmVyIiwgInNlbGVjdCIsICJ0aW1lIiwgImR5bmFtaWNfbXVsdGlzZWxlY3QiXQogICAgcmVxdWlyZWQ6IGJvb2wgPSBUcnVlCiAgICBvcHRpb25zOiBPcHRpb25hbFtsaXN0W3N0cl1dID0gTm9uZQogICAgcGxhY2Vob2xkZXI6IE9wdGlvbmFsW3N0cl0gPSBOb25lCiAgICBoZWxwOiBPcHRpb25hbFtzdHJdID0gTm9uZQogICAgIyBkeW5hbWljX211bHRpc2VsZWN0IOWwiOeUqO+8muWJjeerr+S+neatpOWAvOaxuuWumuimgeWQkeWTquWAiyBBUEkg5oqT5Y2z5pmC6YG46aCF5riF5Zau77yMCiAgICAjIOebruWJjeWPquaciSAiZXh0ZW5zaW9ucyIg5LiA56iu5L6G5rqQ77yM5L+d55WZ5pO05YWF56m66ZaT77yI5pyq5L6G5aaCIGdhdGV3YXkvc291bmQg5riF5Zau77yJCiAgICBzb3VyY2U6IE9wdGlvbmFsW3N0cl0gPSBOb25lCgoKZGVmIF94bWxfZXNjYXBlKHM6IHN0cikgLT4gc3RyOgogICAgcmV0dXJuIChzdHIocykucmVwbGFjZSgiJiIsICImYW1wOyIpLnJlcGxhY2UoIjwiLCAiJmx0OyIpCiAgICAgICAgICAgICAgICAgICAucmVwbGFjZSgiPiIsICImZ3Q7IikucmVwbGFjZSgnIicsICImcXVvdDsiKSkKCgpfV0RBWV9NQVAgPSB7Im1vbi1mcmkiOiAiMi02IiwgIm1vbi1zYXQiOiAiMi03IiwgImFsbCI6ICIxLTcifQpfVElNRV9SRSA9IHJlLmNvbXBpbGUociJeKFswMV1cZHwyWzAtM10pOihbMC01XVxkKSQiKQoKCmRlZiBfcmVxdWlyZSh2YWx1ZXM6IGRpY3QsIGtleTogc3RyLCBsYWJlbDogc3RyKSAtPiBzdHI6CiAgICB2ID0gc3RyKHZhbHVlcy5nZXQoa2V5LCAiIikpLnN0cmlwKCkKICAgIGlmIG5vdCB2OgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoZiLjgIx7bGFiZWx944CN54K65b+F5aGr5qyE5L2NIikKICAgIHJldHVybiB2CgoKZGVmIF9nZW5fdGltZV9yb3V0ZSh2OiBkaWN0KSAtPiBzdHI6CiAgICAiIiLmmYLmrrXot6/nlLHvvJrkuIrnj63mmYLplpPovYnmn5DliIbmqZ8v576k57WE77yM5YW26aSY5pmC6ZaT6L2J6Kqe6Z+z5L+h566x5oiW5YW25LuW6Jmf56K8IiIiCiAgICBuYW1lID0gX3JlcXVpcmUodiwgIm5hbWUiLCAi6KaP5YmH5ZCN56ixIikKICAgIG51bWJlciA9IF9yZXF1aXJlKHYsICJudW1iZXIiLCAi6YCy57ea6Jmf56K8IikKICAgIHN0YXJ0X3RpbWUgPSBfcmVxdWlyZSh2LCAic3RhcnRfdGltZSIsICLkuIrnj63plovlp4siKQogICAgZW5kX3RpbWUgPSBfcmVxdWlyZSh2LCAiZW5kX3RpbWUiLCAi5LiK54+t57WQ5p2fIikKICAgIGluX3RhcmdldCA9IF9yZXF1aXJlKHYsICJpbl9ob3Vyc190YXJnZXQiLCAi5LiK54+t5pmC6ZaT6L2J5o6l55uu5qiZIikKICAgIG91dF90YXJnZXQgPSBfcmVxdWlyZSh2LCAib3V0X29mX2hvdXJzX3RhcmdldCIsICLpnZ7kuIrnj63mmYLplpPovYnmjqXnm67mqJkiKQogICAgZGF5cyA9IHN0cih2LmdldCgiZGF5cyIpIG9yICJtb24tZnJpIikKCiAgICBpZiBub3QgcmUubWF0Y2gociJeXGR7Miw2fSQiLCBudW1iZXIpOgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoIumAsue3muiZn+eivOWPquiDveaYr+aVuOWtl++8iDItNiDnorzvvIkiKQogICAgaWYgbm90IF9USU1FX1JFLm1hdGNoKHN0YXJ0X3RpbWUpIG9yIG5vdCBfVElNRV9SRS5tYXRjaChlbmRfdGltZSk6CiAgICAgICAgcmFpc2UgVmFsdWVFcnJvcigi5pmC6ZaT5qC85byP6aCI54K6IEhIOk1N77yM5L6L77yaMDk6MDAiKQogICAgaWYgZGF5cyBub3QgaW4gX1dEQVlfTUFQOgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoIumBqeeUqOaXpeWPg+aVuOS4jeWQiOazlSIpCiAgICBpZiBub3QgcmUubWF0Y2gociJeW1x3XC1dKyQiLCBpbl90YXJnZXQpIG9yIG5vdCByZS5tYXRjaChyIl5bXHdcLV0rJCIsIG91dF90YXJnZXQpOgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoIui9ieaOpeebruaomeWPquiDveaYr+WIhuapn++8j0lWUiDomZ/norzmiJYgZXh0ZW5zaW9uIOWQjeeose+8iOiLseaVuOWtl+OAgeW6lee3muOAgemAo+Wtl+iZn++8iSIpCgogICAgZXh0X25hbWUgPSBfeG1sX2VzY2FwZShuYW1lKQogICAgc3RhcnRfaG91ciA9IHN0YXJ0X3RpbWUuc3BsaXQoIjoiKVswXS5sc3RyaXAoIjAiKSBvciAiMCIKICAgIGVuZF9ob3VyID0gZW5kX3RpbWUuc3BsaXQoIjoiKVswXS5sc3RyaXAoIjAiKSBvciAiMCIKCiAgICByZXR1cm4gZiIiIjxpbmNsdWRlPgogIDxleHRlbnNpb24gbmFtZT0ie2V4dF9uYW1lfSI+CiAgICA8Y29uZGl0aW9uIGZpZWxkPSJkZXN0aW5hdGlvbl9udW1iZXIiIGV4cHJlc3Npb249Il57X3htbF9lc2NhcGUobnVtYmVyKX0kIj4KICAgICAgPGNvbmRpdGlvbiB3ZGF5PSJ7X1dEQVlfTUFQW2RheXNdfSIgaG91cj0ie3N0YXJ0X2hvdXJ9LXtlbmRfaG91cn0iIGJyZWFrPSJvbi1mYWxzZSI+CiAgICAgICAgPGFjdGlvbiBhcHBsaWNhdGlvbj0idHJhbnNmZXIiIGRhdGE9IntfeG1sX2VzY2FwZShpbl90YXJnZXQpfSBYTUwgZGVmYXVsdCIvPgogICAgICA8L2NvbmRpdGlvbj4KICAgICAgPGFjdGlvbiBhcHBsaWNhdGlvbj0idHJhbnNmZXIiIGRhdGE9IntfeG1sX2VzY2FwZShvdXRfdGFyZ2V0KX0gWE1MIGRlZmF1bHQiLz4KICAgIDwvY29uZGl0aW9uPgogIDwvZXh0ZW5zaW9uPgo8L2luY2x1ZGU+CiIiIgoKCmRlZiBfZ2VuX2JsYWNrbGlzdCh2OiBkaWN0KSAtPiBzdHI6CiAgICAiIiLpu5HlkI3llq7vvJrkvobpm7vomZ/norzlkb3kuK3ljbPnm7TmjqXmjpvmlrfvvIzkuI3pgLLlhaXlhbbku5YgZGlhbHBsYW4iIiIKICAgIG5hbWUgPSBfcmVxdWlyZSh2LCAibmFtZSIsICLopo/liYflkI3nqLEiKQogICAgbnVtYmVyc19yYXcgPSBfcmVxdWlyZSh2LCAibnVtYmVycyIsICLlsIHpjpbomZ/norwiKQogICAgbnVtYmVycyA9IFtuLnN0cmlwKCkgZm9yIG4gaW4gbnVtYmVyc19yYXcuc3BsaXQoIiwiKSBpZiBuLnN0cmlwKCldCiAgICBpZiBub3QgbnVtYmVyczoKICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCLoh7PlsJHpnIDopoHkuIDntYTlsIHpjpbomZ/norwiKQogICAgZm9yIG4gaW4gbnVtYmVyczoKICAgICAgICBpZiBub3QgcmUubWF0Y2gociJeW1xkKypdKyQiLCBuKToKICAgICAgICAgICAgcmFpc2UgVmFsdWVFcnJvcihmIuiZn+eivOOAjHtufeOAjeagvOW8j+S4jeWQiOazle+8jOWPquiDveWMheWQq+aVuOWtl+OAgSsg5oiWICoiKQoKICAgIGV4dF9uYW1lID0gX3htbF9lc2NhcGUobmFtZSkKICAgIHBhdHRlcm4gPSAifCIuam9pbihyZS5lc2NhcGUobikgZm9yIG4gaW4gbnVtYmVycykKICAgIHJldHVybiBmIiIiPGluY2x1ZGU+CiAgPGV4dGVuc2lvbiBuYW1lPSJ7ZXh0X25hbWV9Ij4KICAgIDxjb25kaXRpb24gZmllbGQ9ImNhbGxlcl9pZF9udW1iZXIiIGV4cHJlc3Npb249Il4oe3BhdHRlcm59KSQiPgogICAgICA8YWN0aW9uIGFwcGxpY2F0aW9uPSJsb2ciIGRhdGE9IldBUk5JTkcgQmxvY2tlZCBibGFja2xpc3RlZCBjYWxsZXIgJHt7Y2FsbGVyX2lkX251bWJlcn19Ii8+CiAgICAgIDxhY3Rpb24gYXBwbGljYXRpb249Imhhbmd1cCIgZGF0YT0iQ0FMTF9SRUpFQ1RFRCIvPgogICAgPC9jb25kaXRpb24+CiAgPC9leHRlbnNpb24+CjwvaW5jbHVkZT4KIiIiCgoKZGVmIF9nZW5faW50ZXJuYWxfZXh0ZW5zaW9uKHY6IGRpY3QpIC0+IHN0cjoKICAgICIiIgogICAg5YWn57ea5LqS5pKl77ya6K6T5Yu+6YG455qE5YiG5qmf5Y+v5Lul5Zyo6YCZ5YCLIGNvbnRleHQg5YWn5LqS55u455u05pKl44CCCiAgICDliLvmhI/kuI3mr5TnhacgZGVmYXVsdC54bWwg55qEIExvY2FsX0V4dGVuc2lvbiDlr6vmrbvplovmlL7mlbTmrrXomZ/norzljYDplpMKICAgIO+8iF4oMVswLTldezN9KSTvvInvvIzogIzmmK/lj6rplovmlL7kvb/nlKjogIXmmI7norrli77pgbjnmoTliIbmqZ/muIXllq7vvIzpgb/lhY3lnKjoh6roqIIKICAgIGNvbnRleHTvvIjlpoIgVEMtQUNTQkPvvInmhI/lpJbplovmlL7kuI3oqbLorpPpgJnlgIvkvobmupDmkqXmiZPnmoTliIbmqZ/jgIIKICAgICIiIgogICAgbmFtZSA9IF9yZXF1aXJlKHYsICJuYW1lIiwgIuimj+WJh+WQjeeosSIpCiAgICBleHRfcmF3ID0gX3JlcXVpcmUodiwgImV4dGVuc2lvbnMiLCAi5YWB6Kix5pKl5omT55qE5YiG5qmfIikKICAgIGV4dGVuc2lvbnMgPSBbZS5zdHJpcCgpIGZvciBlIGluIGV4dF9yYXcuc3BsaXQoIiwiKSBpZiBlLnN0cmlwKCldCiAgICBpZiBub3QgZXh0ZW5zaW9uczoKICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCLoh7PlsJHpnIDopoHli77pgbjkuIDmlK/liIbmqZ8iKQogICAgZm9yIGUgaW4gZXh0ZW5zaW9uczoKICAgICAgICBpZiBub3QgcmUubWF0Y2gociJeXGR7Miw4fSQiLCBlKToKICAgICAgICAgICAgcmFpc2UgVmFsdWVFcnJvcihmIuWIhuapn+iZn+eivOOAjHtlfeOAjeagvOW8j+S4jeWQiOazle+8jOWPquiDveaYr+aVuOWtlyIpCgogICAgdGltZW91dF9yYXcgPSBfcmVxdWlyZSh2LCAiY2FsbF90aW1lb3V0IiwgIumAmuipsemAvuaZguenkuaVuCIpCiAgICB0cnk6CiAgICAgICAgdGltZW91dCA9IGludCh0aW1lb3V0X3JhdykKICAgIGV4Y2VwdCBWYWx1ZUVycm9yOgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoIumAmuipsemAvuaZguenkuaVuOmgiOeCuuaVtOaVuCIpCiAgICBpZiBub3QgKDUgPD0gdGltZW91dCA8PSAzMDApOgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoIumAmuipsemAvuaZguenkuaVuOmgiOS7i+aWvCA1LTMwMCDkuYvplpMiKQoKICAgIG9uX25vX2Fuc3dlciA9IHN0cih2LmdldCgib25fbm9fYW5zd2VyIikgb3IgImhhbmd1cCIpCiAgICBpZiBvbl9ub19hbnN3ZXIgbm90IGluICgiaGFuZ3VwIiwgInZvaWNlbWFpbCIpOgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoIuOAjOaJvuS4jeWIsOS6uuaZguOAjeWPg+aVuOS4jeWQiOazlSIpCgogICAgZXh0X25hbWUgPSBfeG1sX2VzY2FwZShuYW1lKQogICAgcGF0dGVybiA9ICJ8Ii5qb2luKHJlLmVzY2FwZShlKSBmb3IgZSBpbiBleHRlbnNpb25zKQoKICAgIHZvaWNlbWFpbF9hY3Rpb24gPSAiIgogICAgaWYgb25fbm9fYW5zd2VyID09ICJ2b2ljZW1haWwiOgogICAgICAgIHZvaWNlbWFpbF9hY3Rpb24gPSAiIiIKICAgICAgPGFjdGlvbiBhcHBsaWNhdGlvbj0iYW5zd2VyIi8+CiAgICAgIDxhY3Rpb24gYXBwbGljYXRpb249InNsZWVwIiBkYXRhPSIxMDAwIi8+CiAgICAgIDxhY3Rpb24gYXBwbGljYXRpb249ImJyaWRnZSIgZGF0YT0ibG9vcGJhY2svYXBwPXZvaWNlbWFpbDpkZWZhdWx0ICR7ZG9tYWluX25hbWV9ICR7ZGlhbGVkX2V4dGVuc2lvbn0iLz4iIiIKCiAgICByZXR1cm4gZiIiIjxpbmNsdWRlPgogIDxleHRlbnNpb24gbmFtZT0ie2V4dF9uYW1lfSI+CiAgICA8Y29uZGl0aW9uIGZpZWxkPSJkZXN0aW5hdGlvbl9udW1iZXIiIGV4cHJlc3Npb249Il4oe3BhdHRlcm59KSQiPgogICAgICA8YWN0aW9uIGFwcGxpY2F0aW9uPSJleHBvcnQiIGRhdGE9ImRpYWxlZF9leHRlbnNpb249JDEiLz4KICAgICAgPGFjdGlvbiBhcHBsaWNhdGlvbj0ic2V0IiBkYXRhPSJjYWxsX3RpbWVvdXQ9e3RpbWVvdXR9Ii8+CiAgICAgIDxhY3Rpb24gYXBwbGljYXRpb249InNldCIgZGF0YT0iaGFuZ3VwX2FmdGVyX2JyaWRnZT10cnVlIi8+CiAgICAgIDxhY3Rpb24gYXBwbGljYXRpb249InNldCIgZGF0YT0iY29udGludWVfb25fZmFpbD10cnVlIi8+CiAgICAgIDxhY3Rpb24gYXBwbGljYXRpb249ImJyaWRnZSIgZGF0YT0idXNlci8ke3tkaWFsZWRfZXh0ZW5zaW9ufX1AJHt7ZG9tYWluX25hbWV9fSIvPnt2b2ljZW1haWxfYWN0aW9ufQogICAgPC9jb25kaXRpb24+CiAgPC9leHRlbnNpb24+CjwvaW5jbHVkZT4KIiIiCgoKVEVNUExBVEVTID0gewogICAgInRpbWVfcm91dGUiOiB7CiAgICAgICAgImxhYmVsIjogIuaZguautei3r+eUse+8iOS4iuePre+8j+mdnuS4iuePreaZgumWk+WIhua1ge+8iSIsCiAgICAgICAgImRlc2NyaXB0aW9uIjogIuaMh+WumuiZn+eivOWcqOS4iuePreaZguautei9ieWIsOafkOWIhuapny/nvqTntYTvvIzlhbbppJjmmYLplpPovYnliLDoqp7pn7Pkv6HnrrHmiJblhbbku5bomZ/norzjgIIiLAogICAgICAgICJmaWVsZHMiOiBbCiAgICAgICAgICAgIFRlbXBsYXRlRmllbGQoa2V5PSJuYW1lIiwgbGFiZWw9Iuimj+WJh+WQjeeosSIsIHR5cGU9InRleHQiLAogICAgICAgICAgICAgICAgICAgICAgICAgIHBsYWNlaG9sZGVyPSLkvovvvJrlrqLmnI3mmYLmrrXliIbmtYEiKSwKICAgICAgICAgICAgVGVtcGxhdGVGaWVsZChrZXk9Im51bWJlciIsIGxhYmVsPSLpgLLnt5romZ/norwiLCB0eXBlPSJ0ZXh0IiwKICAgICAgICAgICAgICAgICAgICAgICAgICBwbGFjZWhvbGRlcj0i5L6L77yaOTUwMCIsIGhlbHA9IuS9v+eUqOiAheaSpeaJk+aIluWklue3muS+humbu+WRveS4reeahOiZn+eivCIpLAogICAgICAgICAgICBUZW1wbGF0ZUZpZWxkKGtleT0iZGF5cyIsIGxhYmVsPSLpgannlKjml6UiLCB0eXBlPSJzZWxlY3QiLAogICAgICAgICAgICAgICAgICAgICAgICAgIG9wdGlvbnM9WyJtb24tZnJpIiwgIm1vbi1zYXQiLCAiYWxsIl0pLAogICAgICAgICAgICBUZW1wbGF0ZUZpZWxkKGtleT0ic3RhcnRfdGltZSIsIGxhYmVsPSLkuIrnj63plovlp4siLCB0eXBlPSJ0aW1lIiwgcGxhY2Vob2xkZXI9IjA5OjAwIiksCiAgICAgICAgICAgIFRlbXBsYXRlRmllbGQoa2V5PSJlbmRfdGltZSIsIGxhYmVsPSLkuIrnj63ntZDmnZ8iLCB0eXBlPSJ0aW1lIiwgcGxhY2Vob2xkZXI9IjE4OjAwIiksCiAgICAgICAgICAgIFRlbXBsYXRlRmllbGQoa2V5PSJpbl9ob3Vyc190YXJnZXQiLCBsYWJlbD0i5LiK54+t5pmC6ZaT6L2J5o6l55uu5qiZIiwgdHlwZT0idGV4dCIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9IuS+i++8mjEwMDEg5oiW576k57WEL0lWUiDomZ/norwiKSwKICAgICAgICAgICAgVGVtcGxhdGVGaWVsZChrZXk9Im91dF9vZl9ob3Vyc190YXJnZXQiLCBsYWJlbD0i6Z2e5LiK54+t5pmC6ZaT6L2J5o6l55uu5qiZIiwgdHlwZT0idGV4dCIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9IuS+i++8mjk4ODjvvIjoqp7pn7Pkv6HnrrHlhaXlj6PvvIkiKSwKICAgICAgICBdLAogICAgICAgICJnZW5lcmF0b3IiOiBfZ2VuX3RpbWVfcm91dGUsCiAgICB9LAogICAgImJsYWNrbGlzdCI6IHsKICAgICAgICAibGFiZWwiOiAi6buR5ZCN5Zau77yI5bCB6Y6W5L6G6Zu777yJIiwKICAgICAgICAiZGVzY3JpcHRpb24iOiAi5L6G6Zu76Jmf56K856ym5ZCI5riF5Zau5pmC55u05o6l5o6b5pa377yM5LiN5pyD6YCy5YWl5YiG5qmf44CB576k57WE5oiWIElWUuOAgiIsCiAgICAgICAgImZpZWxkcyI6IFsKICAgICAgICAgICAgVGVtcGxhdGVGaWVsZChrZXk9Im5hbWUiLCBsYWJlbD0i6KaP5YmH5ZCN56ixIiwgdHlwZT0idGV4dCIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9IuS+i++8mumot+aTvumbu+ipseWwgemOliIpLAogICAgICAgICAgICBUZW1wbGF0ZUZpZWxkKGtleT0ibnVtYmVycyIsIGxhYmVsPSLlsIHpjpbomZ/norzvvIjpgJfomZ/liIbpmpTvvIkiLCB0eXBlPSJ0ZXh0IiwKICAgICAgICAgICAgICAgICAgICAgICAgICBwbGFjZWhvbGRlcj0iMDkxMjM0NTY3OCwwMjg3NjU0MzIxIiksCiAgICAgICAgXSwKICAgICAgICAiZ2VuZXJhdG9yIjogX2dlbl9ibGFja2xpc3QsCiAgICB9LAogICAgImludGVybmFsX2V4dGVuc2lvbiI6IHsKICAgICAgICAibGFiZWwiOiAi5YWn57ea5LqS5pKl77yI6ZmQ5a6a5YiG5qmf5riF5Zau77yJIiwKICAgICAgICAiZGVzY3JpcHRpb24iOiAi6K6T5Yu+6YG455qE5YiG5qmf5Y+v5Lul5Zyo6YCZ5YCLIGNvbnRleHQg5YWn5LqS55u455u05pKl77yM5om+5LiN5Yiw5Lq65pmC5Y+v6YG45pOH5o6b5pa35oiW6L2J6Kqe6Z+z5L+h566x44CCIiwKICAgICAgICAiZmllbGRzIjogWwogICAgICAgICAgICBUZW1wbGF0ZUZpZWxkKGtleT0ibmFtZSIsIGxhYmVsPSLopo/liYflkI3nqLEiLCB0eXBlPSJ0ZXh0IiwKICAgICAgICAgICAgICAgICAgICAgICAgICBwbGFjZWhvbGRlcj0i5L6L77yaVEMtQUNTQkMg5YWn57ea5LqS5pKlIiksCiAgICAgICAgICAgIFRlbXBsYXRlRmllbGQoa2V5PSJleHRlbnNpb25zIiwgbGFiZWw9IuWFgeioseaSpeaJk+eahOWIhuapnyIsIHR5cGU9ImR5bmFtaWNfbXVsdGlzZWxlY3QiLAogICAgICAgICAgICAgICAgICAgICAgICAgIHNvdXJjZT0iZXh0ZW5zaW9ucyIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgaGVscD0i5Y+q5pyJ5Yu+6YG455qE5YiG5qmf5omN6IO95Zyo6YCZ5YCLIGNvbnRleHQg6KKr5pKl5omT77yM5pyq5Yu+6YG455qE5YiG5qmf5Y2z5L2/5a2Y5Zyo5Lmf5pKl5LiN6YCaIiksCiAgICAgICAgICAgIFRlbXBsYXRlRmllbGQoa2V5PSJjYWxsX3RpbWVvdXQiLCBsYWJlbD0i6YCa6Kmx6YC+5pmC56eS5pW4IiwgdHlwZT0ibnVtYmVyIiwKICAgICAgICAgICAgICAgICAgICAgICAgICBwbGFjZWhvbGRlcj0iMzAiLCBoZWxwPSLlsI3mlrnpn7/piLTlpJrkuYXmspLmjqXnrpflpLHmlZfvvIg1LTMwMCDnp5LvvIkiKSwKICAgICAgICAgICAgVGVtcGxhdGVGaWVsZChrZXk9Im9uX25vX2Fuc3dlciIsIGxhYmVsPSLmib7kuI3liLDkurrmmYIiLCB0eXBlPSJzZWxlY3QiLAogICAgICAgICAgICAgICAgICAgICAgICAgIG9wdGlvbnM9WyJoYW5ndXAiLCAidm9pY2VtYWlsIl0pLAogICAgICAgIF0sCiAgICAgICAgImdlbmVyYXRvciI6IF9nZW5faW50ZXJuYWxfZXh0ZW5zaW9uLAogICAgfSwKfQoKCmRlZiBfZ2VuZXJhdGVfeG1sKHRlbXBsYXRlX2lkOiBzdHIsIHZhbHVlczogZGljdCkgLT4gc3RyOgogICAgdHBsID0gVEVNUExBVEVTLmdldCh0ZW1wbGF0ZV9pZCkKICAgIGlmIG5vdCB0cGw6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbihzdGF0dXNfY29kZT00MDQsIGRldGFpbD1mIuevhOacrOS4jeWtmOWcqO+8mnt0ZW1wbGF0ZV9pZH0iKQogICAgdHJ5OgogICAgICAgIGJvZHkgPSB0cGxbImdlbmVyYXRvciJdKHZhbHVlcykKICAgIGV4Y2VwdCBWYWx1ZUVycm9yIGFzIGU6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbihzdGF0dXNfY29kZT00MDAsIGRldGFpbD1zdHIoZSkpCiAgICBtZXRhID0ganNvbi5kdW1wcyh7InRlbXBsYXRlX2lkIjogdGVtcGxhdGVfaWQsICJ2YWx1ZXMiOiB2YWx1ZXN9LCBlbnN1cmVfYXNjaWk9RmFsc2UpCiAgICByZXR1cm4gZiI8IS0tIERBU0hCT0FSRF9DVVNUT01fTUVUQToge21ldGF9IC0tPlxue2JvZHl9IgoKCiMg4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQCiMgUHlkYW50aWMg6KuL5rGC5qih5Z6LCiMg4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQCgpjbGFzcyBUZW1wbGF0ZVByZXZpZXdSZXF1ZXN0KEJhc2VNb2RlbCk6CiAgICB0ZW1wbGF0ZV9pZDogc3RyCiAgICB2YWx1ZXM6IGRpY3QKCgpjbGFzcyBUZW1wbGF0ZUNyZWF0ZVJlcXVlc3QoQmFzZU1vZGVsKToKICAgIHRlbXBsYXRlX2lkOiBzdHIKICAgIGZpbGVuYW1lOiBzdHIKICAgIGNvbnRleHQ6IHN0ciA9ICJkZWZhdWx0IgogICAgdmFsdWVzOiBkaWN0CgogICAgQGZpZWxkX3ZhbGlkYXRvcigiZmlsZW5hbWUiKQogICAgQGNsYXNzbWV0aG9kCiAgICBkZWYgdmFsaWRfZmlsZW5hbWUoY2xzLCB2KToKICAgICAgICBpZiBub3QgcmUubWF0Y2gociJeW1x3XC1dK1wueG1sJCIsIHYpOgogICAgICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCLmqpTlkI3lj6rog73lkKvoi7HmlbjlrZfjgIHlupXnt5rjgIHpgKPlrZfomZ/vvIzlia/mqpTlkI3poIjngrogLnhtbCIpCiAgICAgICAgcmV0dXJuIHYKCiAgICBAZmllbGRfdmFsaWRhdG9yKCJjb250ZXh0IikKICAgIEBjbGFzc21ldGhvZAogICAgZGVmIHZhbGlkX2NvbnRleHRfZm9ybWF0KGNscywgdik6CiAgICAgICAgIyAyMDI2LTA4LTExIOS/ruW+qe+8muiIiueJiOWvq+atuyBMaXRlcmFsWyJkZWZhdWx0IiwicHVibGljIl3vvIzlsI7oh7Tnr4TmnKzmqKHlvI8KICAgICAgICAjIOWujOWFqOeEoeazleWvq+WFpSBkZWZhdWx0L3B1YmxpYyDku6XlpJbnmoToh6roqIIgY29udGV4dO+8iOS+i+WmgiBUQy1BQ1NCQ++8ie+8jAogICAgICAgICMg6Lef5YmN56uv44CMQ29udGV4dCDpgbjllq7mlK/mj7Tku7vmhI/ml6LmnIkgY29udGV4dOOAjeeahOWvpumam+ihjOeCuuS6kuebuOefm+ebvuOAggogICAgICAgICMg6YCZ6KOh5YWI5Y+q6amX6K2J5qC85byP77yM44CM5piv5ZCm55yf55qE5a2Y5Zyo44CN55qE5qqi5p+l5pS+5ZyoIGhhbmRsZXIg6KOh77yI6KaLCiAgICAgICAgIyBjcmVhdGVfZnJvbV90ZW1wbGF0ZSgp77yJ77yM5Zug54K66YKj6YKK5omN5pyJIGZpbGVzeXN0ZW0g5a2Y5Y+W5pmC5qmf44CCCiAgICAgICAgY3R4ID0gKHYgb3IgIiIpLnN0cmlwKCkKICAgICAgICBpZiBub3QgY3R4IG9yIG5vdCByZS5tYXRjaChyIl5bXHdcLV0rJCIsIGN0eCk6CiAgICAgICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoImNvbnRleHQg5ZCN56ix5qC85byP5LiN5ZCI5rOVIikKICAgICAgICByZXR1cm4gY3R4CgoKY2xhc3MgVGVtcGxhdGVVcGRhdGVSZXF1ZXN0KEJhc2VNb2RlbCk6CiAgICBwYXRoOiBzdHIKICAgIHRlbXBsYXRlX2lkOiBzdHIKICAgIHZhbHVlczogZGljdAoKCiMg4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQCiMg6Lev5b6R5a6J5YWo5qqi5p+lCiMg4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQCgpkZWYgX2Fzc2VydF9hbGxvd2VkX3BhdGgocGF0aDogc3RyKSAtPiBOb25lOgogICAgaWYgbm90IHBhdGguc3RhcnRzd2l0aChESUFMUExBTl9ST09UICsgIi8iKToKICAgICAgICByYWlzZSBIVFRQRXhjZXB0aW9uKHN0YXR1c19jb2RlPTQwMywgZGV0YWlsPSLkuI3lhYHoqLHlrZjlj5bmraTot6/lvpEiKQoKCmRlZiBfYXNzZXJ0X25vdF9tYW5hZ2VkKGZwYXRoOiBzdHIpIC0+IE5vbmU6CiAgICBmbmFtZSA9IG9zLnBhdGguYmFzZW5hbWUoZnBhdGgpCiAgICBpZiBmbmFtZS5zdGFydHN3aXRoKE1BTkFHRURfUFJFRklYRVMpIG9yIGZuYW1lIGluIE1BTkFHRURfRklMRU5BTUVTOgogICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oCiAgICAgICAgICAgIHN0YXR1c19jb2RlPTQwMywKICAgICAgICAgICAgZGV0YWlsPSLmraTmqpTmoYjnlLHlhbbku5bnrqHnkIbpoIHpnaLntq3orbfvvIjot6/nlLHopo/liYfvvI/nvqTntYTvvI9JVlLvvI/ns7vntbHlhaflu7rvvInvvIzoq4voh7PlsI3mh4npoIHpnaLmk43kvZwiLAogICAgICAgICkKCgojIOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkAojIEFQSSDnq6/pu54KIyDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZAKCkByb3V0ZXIuZ2V0KCIvYXBpL2RpYWxwbGFuL2N1c3RvbS90ZW1wbGF0ZXMiLCBkZXBlbmRlbmNpZXM9W0RlcGVuZHMocmVxdWlyZV9wZXJtaXNzaW9uKE1vZHVsZS5ESUFMUExBTiwgInJlYWQiKSldKQpkZWYgbGlzdF90ZW1wbGF0ZXMoKToKICAgIHJldHVybiB7CiAgICAgICAgInRlbXBsYXRlcyI6IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICAgImlkIjogdGlkLAogICAgICAgICAgICAgICAgImxhYmVsIjogdFsibGFiZWwiXSwKICAgICAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6IHQuZ2V0KCJkZXNjcmlwdGlvbiIsICIiKSwKICAgICAgICAgICAgICAgICJmaWVsZHMiOiBbZi5tb2RlbF9kdW1wKCkgZm9yIGYgaW4gdFsiZmllbGRzIl1dLAogICAgICAgICAgICB9CiAgICAgICAgICAgIGZvciB0aWQsIHQgaW4gVEVNUExBVEVTLml0ZW1zKCkKICAgICAgICBdCiAgICB9CgoKQHJvdXRlci5nZXQoIi9hcGkvZGlhbHBsYW4vY3VzdG9tL2V4dGVuc2lvbi1vcHRpb25zIiwgZGVwZW5kZW5jaWVzPVtEZXBlbmRzKHJlcXVpcmVfcGVybWlzc2lvbihNb2R1bGUuRElBTFBMQU4sICJyZWFkIikpXSkKZGVmIGxpc3RfZXh0ZW5zaW9uX29wdGlvbnMoKToKICAgICIiIgogICAg6LyV6YeP5YiG5qmf5riF5Zau77yM5Y+q57Wm56+E5pys6KGo5Zau44CM5Yu+6YG45YiG5qmf44CN55So6YCU77ya5Y+q5Zue5YKzIGlkICsg6aGv56S65ZCN56ix44CCCgogICAg5Yi75oSP5LiN6YeN55SoIC9hcGkvZXh0ZW5zaW9ucy9saXN077yITW9kdWxlLkVYVEVOU0lPTlPvvInvvJrpgqPmlK8gQVBJIOacg+aYjueivOWbnuWCswogICAgU0lQIOWvhueivO+8j+iqnumfs+S/oeeuseWvhueivO+8jOWWrue0lOeCuuS6hueVq+mdouS4iuWLvumBuOWIhuapn+iZn+eivOWNu+aKiuWvhueivOS4gOS9teS4i+i8ieWIsAogICAg5YmN56uv5LiN5ZCI55CG77yb5LiU5qyK6ZmQ55+p6Zmj5pivIDE5IOaooee1hOWQhOiHqueNqOeri+ioreioiO+8jOaTjeS9nCBEaWFscGxhbiDpoIHpnaLnmoTkuroKICAgIOS4jeS4gOWumuacie+8iOS5n+S4jeaHieipsumcgOimge+8iUV4dGVuc2lvbnMg5qih57WE55qE6K6A5Y+W5qyK6ZmQ44CC6YCZ5pSv56uv6bue5o6b5ZyoCiAgICBNb2R1bGUuRElBTFBMQU4g5bqV5LiL77yM6Lef6aCB6Z2i5pys6Lqr5ZCM5LiA5YCL5qyK6ZmQ5qih57WE77yM5LiN6ZyA6KaB6Leo5qih57WE5qyK6ZmQ44CCCiAgICAiIiIKICAgIHJlc3VsdCA9IFtdCiAgICBmb3IgZmlsZXBhdGggaW4gc29ydGVkKGdsb2IuZ2xvYihmIntFWFRfRElSfS8qLnhtbCIpKToKICAgICAgICB0cnk6CiAgICAgICAgICAgIHRyZWUgPSBldHJlZS5wYXJzZShmaWxlcGF0aCkKICAgICAgICAgICAgdXNlciA9IHRyZWUuZmluZCgnLi8vdXNlcicpCiAgICAgICAgICAgIGlmIHVzZXIgaXMgTm9uZToKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGV4dF9pZCA9IHVzZXIuZ2V0KCdpZCcsICcnKS5zdHJpcCgpCiAgICAgICAgICAgIGlmIG5vdCBleHRfaWQgb3Igbm90IGV4dF9pZC5pc2RpZ2l0KCk6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICB2YXJpYWJsZXMgPSB7di5nZXQoJ25hbWUnKTogdi5nZXQoJ3ZhbHVlJykgZm9yIHYgaW4gdHJlZS5maW5kYWxsKCcuLy92YXJpYWJsZXMvdmFyaWFibGUnKX0KICAgICAgICAgICAgcmVzdWx0LmFwcGVuZCh7CiAgICAgICAgICAgICAgICAiaWQiOiBleHRfaWQsCiAgICAgICAgICAgICAgICAiY2FsbGVyX2lkX25hbWUiOiB2YXJpYWJsZXMuZ2V0KCdlZmZlY3RpdmVfY2FsbGVyX2lkX25hbWUnLCAnJykgb3IgZXh0X2lkLAogICAgICAgICAgICB9KQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICByZXR1cm4geyJleHRlbnNpb25zIjogcmVzdWx0fQoKCkByb3V0ZXIuZ2V0KCIvYXBpL2RpYWxwbGFuL2N1c3RvbS9maWxlcyIsIGRlcGVuZGVuY2llcz1bRGVwZW5kcyhyZXF1aXJlX3Blcm1pc3Npb24oTW9kdWxlLkRJQUxQTEFOLCAicmVhZCIpKV0pCmRlZiBsaXN0X2N1c3RvbV9maWxlcygpOgogICAgIiIi5YiX5Ye65omA5pyJ6Z2e5YW25LuW6aCB6Z2i566h55CG55qE6Ieq5a6a576pIGRpYWxwbGFuIOaqlOahiOOAggoKICAgIDIwMjYtMDgtMTEg5L+u5b6p77ya6IiK54mI5a+r5q275Y+q5o6DICgiZGVmYXVsdCIsICJwdWJsaWMiKSDlhanlgIsgY29udGV4dO+8jAogICAg5bCO6Ie05a+r6YCy5YW25LuW6Ieq6KiCIGNvbnRleHTvvIjlpoIgVEMtQUNTQkPvvInnmoTmqpTmoYjlrozlhajkuI3mnIPlh7rnj77lnKjpgJnlgIvliJfooajigJTigJQKICAgIOaUueaIkOaOg+aPjyBsaXN0X2NvbnRleHRzKCkg5Zue5YKz55qE5omA5pyJ55yf5a+m5a2Y5ZyoIGNvbnRleHTjgIIKICAgICIiIgogICAgZnJvbSByb3V0ZXJzLmRpYWxwbGFuX3JvdXRlcyBpbXBvcnQgbGlzdF9jb250ZXh0cyBhcyBfbGlzdF9kaWFscGxhbl9jb250ZXh0cwogICAgcmVzdWx0ID0gW10KICAgIGZvciBjb250ZXh0IGluIF9saXN0X2RpYWxwbGFuX2NvbnRleHRzKCk6CiAgICAgICAgcGF0dGVybiA9IG9zLnBhdGguam9pbihESUFMUExBTl9ST09ULCBjb250ZXh0LCAiKi54bWwiKQogICAgICAgIGZvciBmcGF0aCBpbiBzb3J0ZWQoZ2xvYi5nbG9iKHBhdHRlcm4pKToKICAgICAgICAgICAgZm5hbWUgPSBvcy5wYXRoLmJhc2VuYW1lKGZwYXRoKQogICAgICAgICAgICBpZiBmbmFtZS5zdGFydHN3aXRoKE1BTkFHRURfUFJFRklYRVMpIG9yIGZuYW1lIGluIE1BTkFHRURfRklMRU5BTUVTOgogICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgd2l0aCBvcGVuKGZwYXRoLCAiciIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgICAgICAgICAgICAgY29udGVudCA9IGYucmVhZCgpCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgICAgIHJlc3VsdC5hcHBlbmQoewogICAgICAgICAgICAgICAgICAgICJmaWxlbmFtZSI6IGZuYW1lLCAicGF0aCI6IGZwYXRoLCAiY29udGV4dCI6IGNvbnRleHQsCiAgICAgICAgICAgICAgICAgICAgImVycm9yIjogc3RyKGUpLCAiaXNfdGVtcGxhdGUiOiBGYWxzZSwKICAgICAgICAgICAgICAgICAgICAiZXh0ZW5zaW9ucyI6IFtdLCAiZGVzdGluYXRpb25zIjogW10sCiAgICAgICAgICAgICAgICB9KQogICAgICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgICAgIG0gPSBNRVRBX1JFLnNlYXJjaChjb250ZW50KQogICAgICAgICAgICBpc190ZW1wbGF0ZSwgdGVtcGxhdGVfaWQsIHRlbXBsYXRlX2xhYmVsID0gRmFsc2UsIE5vbmUsIE5vbmUKICAgICAgICAgICAgaWYgbToKICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICBtZXRhID0ganNvbi5sb2FkcyhtLmdyb3VwKDEpKQogICAgICAgICAgICAgICAgICAgIHRlbXBsYXRlX2lkID0gbWV0YS5nZXQoInRlbXBsYXRlX2lkIikKICAgICAgICAgICAgICAgICAgICBpZiB0ZW1wbGF0ZV9pZCBpbiBURU1QTEFURVM6CiAgICAgICAgICAgICAgICAgICAgICAgIGlzX3RlbXBsYXRlID0gVHJ1ZQogICAgICAgICAgICAgICAgICAgICAgICB0ZW1wbGF0ZV9sYWJlbCA9IFRFTVBMQVRFU1t0ZW1wbGF0ZV9pZF1bImxhYmVsIl0KICAgICAgICAgICAgICAgIGV4Y2VwdCAoanNvbi5KU09ORGVjb2RlRXJyb3IsIEtleUVycm9yKToKICAgICAgICAgICAgICAgICAgICBwYXNzCgogICAgICAgICAgICBleHRlbnNpb25zID0gcmUuZmluZGFsbChyJzxleHRlbnNpb25ccytuYW1lPSIoW14iXSspIicsIGNvbnRlbnQpCiAgICAgICAgICAgIGRlc3RpbmF0aW9ucyA9IHJlLmZpbmRhbGwoCiAgICAgICAgICAgICAgICByJzxjb25kaXRpb25ccytmaWVsZD0iZGVzdGluYXRpb25fbnVtYmVyIlxzK2V4cHJlc3Npb249IihbXiJdKikiJywgY29udGVudAogICAgICAgICAgICApCgogICAgICAgICAgICByZXN1bHQuYXBwZW5kKHsKICAgICAgICAgICAgICAgICJmaWxlbmFtZSI6IGZuYW1lLAogICAgICAgICAgICAgICAgInBhdGgiOiBmcGF0aCwKICAgICAgICAgICAgICAgICJjb250ZXh0IjogY29udGV4dCwKICAgICAgICAgICAgICAgICJzaXplIjogb3MucGF0aC5nZXRzaXplKGZwYXRoKSwKICAgICAgICAgICAgICAgICJpc190ZW1wbGF0ZSI6IGlzX3RlbXBsYXRlLAogICAgICAgICAgICAgICAgInRlbXBsYXRlX2lkIjogdGVtcGxhdGVfaWQsCiAgICAgICAgICAgICAgICAidGVtcGxhdGVfbGFiZWwiOiB0ZW1wbGF0ZV9sYWJlbCwKICAgICAgICAgICAgICAgICJleHRlbnNpb25zIjogZXh0ZW5zaW9ucywKICAgICAgICAgICAgICAgICJkZXN0aW5hdGlvbnMiOiBkZXN0aW5hdGlvbnMsCiAgICAgICAgICAgIH0pCiAgICByZXR1cm4geyJmaWxlcyI6IHJlc3VsdCwgInRvdGFsIjogbGVuKHJlc3VsdCl9CgoKQHJvdXRlci5nZXQoIi9hcGkvZGlhbHBsYW4vY3VzdG9tL2ZpbGUiLCBkZXBlbmRlbmNpZXM9W0RlcGVuZHMocmVxdWlyZV9wZXJtaXNzaW9uKE1vZHVsZS5ESUFMUExBTiwgInJlYWQiKSldKQpkZWYgcGFyc2VfY3VzdG9tX2ZpbGUocGF0aDogc3RyKToKICAgICIiIuiugOaqlOS4puWYl+ippuWPjeinoyBNRVRB77yM6K6T56+E5pys5bu656uL55qE5qqU5qGI5Y+v5Lul5Zue5Yiw6KGo5Zau57eo6Lyv77yMCiAgICDpnZ7nr4TmnKzmqpTmoYjliYflm57lgrMgZWRpdGFibGVfYXNfdGVtcGxhdGU9RmFsc2XvvIzliY3nq6/mk5rmraTmlLnnlKjmiYvli5UgcmF3IOe3qOi8r+WZqOOAggogICAgIiIiCiAgICBfYXNzZXJ0X2FsbG93ZWRfcGF0aChwYXRoKQogICAgX2Fzc2VydF9ub3RfbWFuYWdlZChwYXRoKQogICAgaWYgbm90IG9zLnBhdGguZXhpc3RzKHBhdGgpOgogICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oc3RhdHVzX2NvZGU9NDA0LCBkZXRhaWw9IuaqlOahiOS4jeWtmOWcqCIpCgogICAgd2l0aCBvcGVuKHBhdGgsICJyIiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBjb250ZW50ID0gZi5yZWFkKCkKCiAgICBtID0gTUVUQV9SRS5zZWFyY2goY29udGVudCkKICAgIGlmIG5vdCBtOgogICAgICAgIHJldHVybiB7ImVkaXRhYmxlX2FzX3RlbXBsYXRlIjogRmFsc2UsICJjb250ZW50IjogY29udGVudH0KICAgIHRyeToKICAgICAgICBtZXRhID0ganNvbi5sb2FkcyhtLmdyb3VwKDEpKQogICAgICAgIHRlbXBsYXRlX2lkID0gbWV0YS5nZXQoInRlbXBsYXRlX2lkIikKICAgICAgICBpZiB0ZW1wbGF0ZV9pZCBub3QgaW4gVEVNUExBVEVTOgogICAgICAgICAgICByZXR1cm4geyJlZGl0YWJsZV9hc190ZW1wbGF0ZSI6IEZhbHNlLCAiY29udGVudCI6IGNvbnRlbnR9CiAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgImVkaXRhYmxlX2FzX3RlbXBsYXRlIjogVHJ1ZSwKICAgICAgICAgICAgInRlbXBsYXRlX2lkIjogdGVtcGxhdGVfaWQsCiAgICAgICAgICAgICJ2YWx1ZXMiOiBtZXRhLmdldCgidmFsdWVzIiwge30pLAogICAgICAgICAgICAiY29udGVudCI6IGNvbnRlbnQsCiAgICAgICAgfQogICAgZXhjZXB0IChqc29uLkpTT05EZWNvZGVFcnJvciwgS2V5RXJyb3IpOgogICAgICAgIHJldHVybiB7ImVkaXRhYmxlX2FzX3RlbXBsYXRlIjogRmFsc2UsICJjb250ZW50IjogY29udGVudH0KCgpAcm91dGVyLnBvc3QoIi9hcGkvZGlhbHBsYW4vY3VzdG9tL3ByZXZpZXciLCBkZXBlbmRlbmNpZXM9W0RlcGVuZHMocmVxdWlyZV9wZXJtaXNzaW9uKE1vZHVsZS5ESUFMUExBTiwgInJlYWQiKSldKQpkZWYgcHJldmlld190ZW1wbGF0ZShyZXE6IFRlbXBsYXRlUHJldmlld1JlcXVlc3QpOgogICAgIiIi5LiN5a+r5qqU77yM5Y+q5Zue5YKz55Si55Sf55qEIFhNTCDkvpvliY3nq6/jgIzpgLLpmo4gWE1MIOmgkOimveOAjeS9v+eUqCIiIgogICAgeG1sID0gX2dlbmVyYXRlX3htbChyZXEudGVtcGxhdGVfaWQsIHJlcS52YWx1ZXMpCiAgICByZXR1cm4geyJ4bWwiOiB4bWx9CgoKQHJvdXRlci5wb3N0KCIvYXBpL2RpYWxwbGFuL2N1c3RvbS9jcmVhdGUiLCBkZXBlbmRlbmNpZXM9W0RlcGVuZHMocmVxdWlyZV9wZXJtaXNzaW9uKE1vZHVsZS5ESUFMUExBTiwgImNyZWF0ZSIpKV0pCmRlZiBjcmVhdGVfZnJvbV90ZW1wbGF0ZShyZXE6IFRlbXBsYXRlQ3JlYXRlUmVxdWVzdCk6CiAgICBmcm9tIHJvdXRlcnMuZGlhbHBsYW5fcm91dGVzIGltcG9ydCBsaXN0X2NvbnRleHRzIGFzIF9saXN0X2RpYWxwbGFuX2NvbnRleHRzCiAgICBpZiByZXEuY29udGV4dCBub3QgaW4gX2xpc3RfZGlhbHBsYW5fY29udGV4dHMoKToKICAgICAgICByYWlzZSBIVFRQRXhjZXB0aW9uKAogICAgICAgICAgICBzdGF0dXNfY29kZT00MDAsCiAgICAgICAgICAgIGRldGFpbD1mImNvbnRleHTjgIx7cmVxLmNvbnRleHR944CN5LiN5a2Y5Zyo5oiW5bCa5pyq6KKrIEZyZWVTd2l0Y2gg5q2j5byP6L6o6K2Y77yMIgogICAgICAgICAgICAgICAgICAgZiLoq4vlhYjliLDjgIzoh6rlrprnvqkgRGlhbHBsYW7jgI3poIHpnaLnmoQgQ29udGV4dCDpgbjllq7lu7rnq4siLAogICAgICAgICkKCiAgICBkcF9kaXIgPSBvcy5wYXRoLmpvaW4oRElBTFBMQU5fUk9PVCwgcmVxLmNvbnRleHQpCiAgICBmcGF0aCA9IG9zLnBhdGguam9pbihkcF9kaXIsIHJlcS5maWxlbmFtZSkKCiAgICBpZiBvcy5wYXRoLmV4aXN0cyhmcGF0aCk6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbihzdGF0dXNfY29kZT00MDksIGRldGFpbD1mIuaqlOahiOW3suWtmOWcqO+8mntmcGF0aH0iKQogICAgX2Fzc2VydF9ub3RfbWFuYWdlZChmcGF0aCkKCiAgICBjb250ZW50ID0gX2dlbmVyYXRlX3htbChyZXEudGVtcGxhdGVfaWQsIHJlcS52YWx1ZXMpCiAgICB2YWxpZGF0ZV94bWwoY29udGVudCkKCiAgICBvcy5tYWtlZGlycyhkcF9kaXIsIGV4aXN0X29rPVRydWUpCiAgICB0cnk6CiAgICAgICAgd2l0aCBvcGVuKGZwYXRoLCAidyIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgICAgIGYud3JpdGUoY29udGVudCkKICAgIGV4Y2VwdCBPU0Vycm9yIGFzIGU6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbihzdGF0dXNfY29kZT01MDAsIGRldGFpbD1mIuWvq+WFpeaqlOahiOWkseaVl++8mntlfSIpCgogICAgdHJ5OgogICAgICAgIHJlbG9hZF9hbmRfdmVyaWZ5KGZwYXRoLCBiYWNrdXBfcGF0aD0iIikKICAgIGV4Y2VwdCBIVFRQRXhjZXB0aW9uOgogICAgICAgIHJvbGxiYWNrX25ld19maWxlKGZwYXRoKQogICAgICAgIHJhaXNlCgogICAgcmV0dXJuIHsib2siOiBUcnVlLCAicGF0aCI6IGZwYXRofQoKCkByb3V0ZXIucHV0KCIvYXBpL2RpYWxwbGFuL2N1c3RvbS9maWxlIiwgZGVwZW5kZW5jaWVzPVtEZXBlbmRzKHJlcXVpcmVfcGVybWlzc2lvbihNb2R1bGUuRElBTFBMQU4sICJ1cGRhdGUiKSldKQpkZWYgdXBkYXRlX2Zyb21fdGVtcGxhdGUocmVxOiBUZW1wbGF0ZVVwZGF0ZVJlcXVlc3QpOgogICAgIiIi5pu05paw5LiA5YCL5Y6f5pys5bCx5piv55Sx56+E5pys5bu656uL55qE5qqU5qGI77yI6YeN5paw55Si55SfIFhNTCDkuKbopoblr6vvvIkiIiIKICAgIF9hc3NlcnRfYWxsb3dlZF9wYXRoKHJlcS5wYXRoKQogICAgX2Fzc2VydF9ub3RfbWFuYWdlZChyZXEucGF0aCkKICAgIGlmIG5vdCBvcy5wYXRoLmV4aXN0cyhyZXEucGF0aCk6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbihzdGF0dXNfY29kZT00MDQsIGRldGFpbD0i5qqU5qGI5LiN5a2Y5ZyoIikKCiAgICBjb250ZW50ID0gX2dlbmVyYXRlX3htbChyZXEudGVtcGxhdGVfaWQsIHJlcS52YWx1ZXMpCiAgICB2YWxpZGF0ZV94bWwoY29udGVudCkKCiAgICBiYWNrdXBfcGF0aCA9IG1ha2VfYmFja3VwKHJlcS5wYXRoKQogICAgdHJ5OgogICAgICAgIHdpdGggb3BlbihyZXEucGF0aCwgInciLCBlbmNvZGluZz0idXRmLTgiKSBhcyBmOgogICAgICAgICAgICBmLndyaXRlKGNvbnRlbnQpCiAgICBleGNlcHQgT1NFcnJvciBhcyBlOgogICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oc3RhdHVzX2NvZGU9NTAwLCBkZXRhaWw9ZiLlr6vlhaXmqpTmoYjlpLHmlZfvvJp7ZX0iKQoKICAgIHJlbG9hZF9hbmRfdmVyaWZ5KHJlcS5wYXRoLCBiYWNrdXBfcGF0aCkKICAgIHJldHVybiB7Im9rIjogVHJ1ZSwgInBhdGgiOiByZXEucGF0aCwgImJhY2t1cCI6IGJhY2t1cF9wYXRofQo=" | base64 -d > routers/dialplan_custom.py

if [ ! -s routers/dialplan_custom.py ]; then
  echo "❌ routers/dialplan_custom.py 覆寫後為空檔案，還原備份並中止" >&2
  cp routers/dialplan_custom.py.pre-update47.bak routers/dialplan_custom.py
  exit 1
fi

# --- 3. static/js/dialplan.js：精確字串替換（4 處）---
echo "[Step 2] 套用 static/js/dialplan.js 改動..."
cp static/js/dialplan.js static/js/dialplan.js.pre-update47.bak

python3 << 'PYEOF_JS'
import sys

path = "static/js/dialplan.js"
with open(path, "r", encoding="utf-8") as f:
    content = f.read()

edits = []

# Edit 1: _dcRenderRoot 新增 async 動態欄位填充
old1 = """function _dcRenderRoot() {
  const root = document.getElementById(_dcMountId);
  if (_dcMode === 'list') {
    root.innerHTML = _dcListPanelHtml();
  } else if (_dcMode === 'pick') {
    root.innerHTML = _dcPickerPanelHtml();
  } else {
    root.innerHTML = _dcFormPanelHtml();
    _dcBindFormEvents();
    _dcUpdatePreview();
  }
}"""
new1 = """function _dcRenderRoot() {
  const root = document.getElementById(_dcMountId);
  if (_dcMode === 'list') {
    root.innerHTML = _dcListPanelHtml();
  } else if (_dcMode === 'pick') {
    root.innerHTML = _dcPickerPanelHtml();
  } else {
    root.innerHTML = _dcFormPanelHtml();
    _dcBindFormEvents();
    _dcUpdatePreview();
    _dcPopulateDynamicFields();
  }
}"""
edits.append(("_dcRenderRoot", old1, new1))

# Edit 2: _dcFieldInputHtml 新增 dynamic_multiselect 型別
old2 = """function _dcFieldInputHtml(field, value) {
  const v = value !== undefined && value !== null ? value : '';
  const common = `id="dc-field-${field.key}" data-key="${field.key}" class="settings-input" style="max-width:320px"`;
  if (field.type === 'select') {"""
new2 = """function _dcFieldInputHtml(field, value) {
  const v = value !== undefined && value !== null ? value : '';
  const common = `id="dc-field-${field.key}" data-key="${field.key}" class="settings-input" style="max-width:320px"`;
  if (field.type === 'dynamic_multiselect') {
    // 選項要向後端即時抓取（如分機清單），此處先給占位容器，
    // 實際內容由 _dcPopulateDynamicFields() 在表單插入 DOM 後非同步填入。
    // data-prefill 保留編輯模式回填用的既有選中值（逗號分隔）。
    return `<div id="dc-field-${field.key}" data-key="${field.key}"
                 data-source="${_escAttr(field.source || '')}"
                 data-prefill="${_escAttr(v)}"
                 style="max-width:420px;border:1px solid var(--border);border-radius:4px;
                        padding:8px;max-height:180px;overflow-y:auto;background:var(--panel2)">
              <div style="font-size:12px;color:var(--muted)">載入中...</div>
            </div>`;
  }
  if (field.type === 'select') {"""
edits.append(("_dcFieldInputHtml", old2, new2))

# Edit 3: _dcBindFormEvents 對 dynamic_multiselect 改綁 change 事件
old3 = """function _dcBindFormEvents() {
  const tpl = _dcCurrentTemplate();
  if (!tpl) return;
  tpl.fields.forEach(f => {
    const el = document.getElementById(`dc-field-${f.key}`);
    if (el) el.addEventListener('input', _dcSchedulePreview);
  });
}"""
new3 = """function _dcBindFormEvents() {
  const tpl = _dcCurrentTemplate();
  if (!tpl) return;
  tpl.fields.forEach(f => {
    const el = document.getElementById(`dc-field-${f.key}`);
    if (!el) return;
    // dynamic_multiselect 的容器本身不是 input，勾選框是事後非同步塞進去的，
    // 用 change 事件冒泡監聽整個容器即可涵蓋所有勾選框，不需要逐一綁定
    const evt = f.type === 'dynamic_multiselect' ? 'change' : 'input';
    el.addEventListener(evt, _dcSchedulePreview);
  });
}"""
edits.append(("_dcBindFormEvents", old3, new3))

# Edit 4: _dcCollectValues 改支援 dynamic_multiselect + 新增兩個輔助函式
old4 = """function _dcCollectValues() {
  const tpl = _dcCurrentTemplate();
  const values = {};
  (tpl?.fields || []).forEach(f => {
    const el = document.getElementById(`dc-field-${f.key}`);
    values[f.key] = el ? el.value.trim() : '';
  });
  return values;
}"""
new4 = """function _dcCollectValues() {
  const tpl = _dcCurrentTemplate();
  const values = {};
  (tpl?.fields || []).forEach(f => {
    if (f.type === 'dynamic_multiselect') {
      const container = document.getElementById(`dc-field-${f.key}`);
      const checked = container
        ? Array.from(container.querySelectorAll('input[type="checkbox"]:checked')).map(cb => cb.value)
        : [];
      values[f.key] = checked.join(',');
      return;
    }
    const el = document.getElementById(`dc-field-${f.key}`);
    values[f.key] = el ? el.value.trim() : '';
  });
  return values;
}

// ── dynamic_multiselect 欄位：非同步載入選項 ─────────────────────────────────
async function _dcPopulateDynamicFields() {
  const tpl = _dcCurrentTemplate();
  if (!tpl) return;
  const dynFields = tpl.fields.filter(f => f.type === 'dynamic_multiselect');

  for (const f of dynFields) {
    const container = document.getElementById(`dc-field-${f.key}`);
    if (!container) continue;

    const prefillRaw = container.getAttribute('data-prefill') || '';
    const prefillSet = new Set(prefillRaw.split(',').map(s => s.trim()).filter(Boolean));

    try {
      let options = [];
      if (f.source === 'extensions') {
        const data = await apiFetch('/api/dialplan/custom/extension-options');
        options = (data && data.extensions) ? data.extensions : [];
      }

      if (!options.length) {
        container.innerHTML = `<div style="font-size:12px;color:var(--muted)">（目前沒有可選項目）</div>`;
        continue;
      }

      const filterId = `dc-filter-${f.key}`;
      const listId   = `dc-list-${f.key}`;
      container.innerHTML = `
        <input id="${filterId}" class="settings-input" style="width:100%;box-sizing:border-box;
               margin-bottom:6px;font-size:12px" placeholder="搜尋分機號碼或名稱..."
               oninput="_dcFilterDynamicOptions('${listId}', this.value)">
        <div id="${listId}">
          ${options.map(o => `
            <label style="display:flex;align-items:center;gap:6px;padding:3px 0;font-size:12px;cursor:pointer"
                   data-search="${_escAttr((o.id + ' ' + (o.caller_id_name || '')).toLowerCase())}">
              <input type="checkbox" value="${_escAttr(o.id)}" ${prefillSet.has(String(o.id)) ? 'checked' : ''}>
              <span>${_escHtml(o.id)}${o.caller_id_name ? ` <span style="color:var(--muted)">(${_escHtml(o.caller_id_name)})</span>` : ''}</span>
            </label>`).join('')}
        </div>`;
    } catch (e) {
      container.innerHTML = `<div style="font-size:12px;color:var(--red)">載入失敗：${_escHtml(e.message)}</div>`;
    }
  }

  // 選項填好後，若編輯模式已有預選值，觸發一次預覽更新
  if (dynFields.length) _dcSchedulePreview();
}

function _dcFilterDynamicOptions(listId, keyword) {
  const kw = (keyword || '').trim().toLowerCase();
  const list = document.getElementById(listId);
  if (!list) return;
  Array.from(list.children).forEach(label => {
    const hay = label.getAttribute('data-search') || '';
    label.style.display = (!kw || hay.includes(kw)) ? 'flex' : 'none';
  });
}"""
edits.append(("_dcCollectValues", old4, new4))

for name, old, new in edits:
    count = content.count(old)
    if count != 1:
        print(f"❌ 比對錨點「{name}」在檔案中出現 {count} 次（預期 1 次），中止，不寫入任何檔案", file=sys.stderr)
        sys.exit(1)
    content = content.replace(old, new)

with open(path, "w", encoding="utf-8") as f:
    f.write(content)

print("  ✓ static/js/dialplan.js 四處改動皆已套用")
PYEOF_JS

if [ $? -ne 0 ]; then
  echo "❌ static/js/dialplan.js 字串替換失敗，還原全部備份並中止" >&2
  cp static/js/dialplan.js.pre-update47.bak static/js/dialplan.js
  cp routers/dialplan_custom.py.pre-update47.bak routers/dialplan_custom.py
  exit 1
fi

# --- 4. 語法驗證 ---
echo "[Step 3] 語法檢查..."
PY=python3
command -v /opt/myapp/venv/bin/python3 >/dev/null 2>&1 && PY=/opt/myapp/venv/bin/python3

$PY -c "import ast; ast.parse(open('routers/dialplan_custom.py').read())" \
  && echo "  ✓ routers/dialplan_custom.py 語法檢查通過" \
  || {
    echo "❌ routers/dialplan_custom.py 語法檢查失敗，還原全部備份" >&2
    cp static/js/dialplan.js.pre-update47.bak static/js/dialplan.js
    cp routers/dialplan_custom.py.pre-update47.bak routers/dialplan_custom.py
    exit 1
  }

if command -v node >/dev/null 2>&1; then
  node -c static/js/dialplan.js \
    && echo "  ✓ static/js/dialplan.js 語法檢查通過" \
    || {
      echo "❌ static/js/dialplan.js 語法檢查失敗，還原全部備份" >&2
      cp static/js/dialplan.js.pre-update47.bak static/js/dialplan.js
      cp routers/dialplan_custom.py.pre-update47.bak routers/dialplan_custom.py
      exit 1
    }
else
  echo "  ⚠ 找不到 node，略過前端語法檢查（建議部署後在瀏覽器 F12 Console 確認無語法錯誤）"
fi

# --- 5. 清掉備份檔（確認語法都過了才清）---
rm -f routers/dialplan_custom.py.pre-update47.bak static/js/dialplan.js.pre-update47.bak

# --- 6. git commit ---
echo "[Step 4] git commit..."
git add routers/dialplan_custom.py static/js/dialplan.js
git status
git commit -m "feat: 新增「內線互撥」自訂 Dialplan 範本（限定分機清單），修復範本模式無法寫入 default/public 以外 context 的既有 bug，新增不含密碼的輕量分機清單端點供表單勾選"

echo ""
echo "======================================================"
echo " ✓ update47.sh 執行完成"
echo ""
git log --oneline -1
echo ""
echo " ⚠️ 本次修改 routers/dialplan_custom.py（後端），依慣例需要重啟服務："
echo "    systemctl restart fs-dashboard"
echo "    static/js/dialplan.js 是純前端檔案，瀏覽器強制重新整理即可，不需要重啟服務"
echo ""
echo " 驗證重點清單："
echo "  1. systemctl restart fs-dashboard 後 systemctl status fs-dashboard 確認正常啟動、無 500"
echo "  2. 確認新端點正常（應回傳分機清單，不含 password/vm_password 欄位）："
echo "     curl -s http://127.0.0.1:3000/api/dialplan/custom/extension-options -H \"Authorization: Bearer <token>\""
echo "  3. 確認既有範本（時段路由/黑名單）仍正常運作，沒有被新改動影響"
echo "  4. 到「自定義 Dialplan」頁面 → 從範本建立 → 應該看到「內線互撥（限定分機清單）」新選項"
echo "  5. 選擇「內線互撥」範本，Context 選 TC-ACSBC（驗證舊 bug 已修復，之前選這個會被 422 擋掉）："
echo "     - 分機勾選框應該正確載入分機清單（不是卡在「載入中...」）"
echo "     - 搜尋框輸入分機號碼應該能篩選"
echo "     - 勾選 1126、1210 後「進階：檢視產生的 Dialplan XML」應該即時更新預覽"
echo "     - 儲存成功後，實際撥打 1126→1210 應該要能接通"
echo "  6. 確認「自定義 Dialplan」列表頁能看到 TC-ACSBC 底下建立的檔案（驗證 list_custom_files 修復）"
echo "  7. 確認 push 前 git status 乾淨、git log 看到本次 feat: commit"
echo "  8. push 由你自己手動執行"
echo "======================================================"
